### ISSUE TITLE
[BUG] Intellisense not working with cross targeting

### ISSUE THREAD

**Issue by matherm-aboehm** [microsoft/vscode-dotnettools#1269]
### Describe the Issue

In recent C# extension v2.34.12 Intellisense is randomly broken when a code file from a project with cross targeting settings (TargetFrameworks property set to more then 1 TFM) is opened.
Sometimes it doesn't show anything on hovering over code and code completion isn't working and sometimes it picks randomly a single or more TFMs from the list (not only the 1st one) and wrongly shows availability of APIs for only these frameworks.
![VSCode_CS_DevKit_intellisense_error](https://github.com/microsoft/vscode-dotnettools/assets/60391995/14712ce5-0ce1-4a61-ae13-05951a55efca)

When I try to restart .NET Language Server, Intellisense stops working at all and the following error is logged to output window:
> [stdout] fail: Microsoft.CodeAnalysis.LanguageServer.ExportProviderBuilder[0]
      c:\Users\xxx\.vscode\extensions\ms-dotnettools.csharp-2.34.12-win32-x64\.xamlTools\Microsoft.VisualStudio.DesignTools.CodeAnalysis.dll with assembly name Microsoft.VisualStudio.DesignTools.CodeAnalysis, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a conflicts with extension loaded from c:\Users\xxx\.vscode\extensions\ms-dotnettools.csharp-2.34.12-win32-x64\.xamlTools
[stdout] fail: Microsoft.CodeAnalysis.LanguageServer.ExportProviderBuilder[0]
      c:\Users\xxx\.vscode\extensions\ms-dotnettools.csharp-2.34.12-win32-x64\.xamlTools\Microsoft.VisualStudio.DesignTools.CodeAnalysis.Diagnostics.dll with assembly name Microsoft.VisualStudio.DesignTools.CodeAnalysis.Diagnostics, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a conflicts with extension loaded from c:\Users\xxx\.vscode\extensions\ms-dotnettools.csharp-2.34.12-win32-x64\.xamlTools

### Environment Information

- OS: Windows_NT x64 10.0.19045
- VSCode Version: 1.89.1 (system setup)
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Datum: 2024-05-07T05:13:33.891Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
- Extension Version: C# Dev Kit v1.7.27, C# v2.34.12
- .NET SDK Version: 8.0.302

**Comment by firedigger** [comment]
I have the same issue. Thought not sure on different target frameworks. In my solution all projects are .NET 8 except for one legacy netstandard2.0 component.

**Comment by estebanbelong** [comment]
Same issue here, started happened very recently. All of our solution is in .NET 6 with some exceptions already on .NET 8
![image](https://github.com/microsoft/vscode-dotnettools/assets/110946570/aec708ed-52a1-41ec-a887-c94fcb27b78a)

**Comment by dibarbet** [comment]
I believe this the same issue as https://github.com/microsoft/vscode-dotnettools/issues/1198 and https://github.com/dotnet/vscode-csharp/issues/7231

This should be fixed in next week's prerelease, will report back here once it is available.

**Comment by dibarbet** [comment]
The 2.39.28 prerelease version of the C# extension was released today - @matherm-aboehm can you check if it fixes the issue?

**Comment by Thorry84** [comment]
I had the exact same issue with the same error when restarting the language server. Updating to the prerelease 2.39.28 fixed the issue for me.

**Comment by firedigger** [comment]
Can confirm the issue is fixed as well on `2.39.28`, can be closed after a normal release I suppose.

**Comment by matherm-aboehm** [comment]
Sorry for late reply, I was on vacation.
It looks like the Intellisense issue is resolved in v2.39.29, although it still switches between random TFM contexts, when VSCode is restarted, which you can see when hitting F12 - Go to definition.
Also the restart of .NET Language Server still shows the same error as initially described.
But the hover texts now shows right information for the code elements, so this is good enough for me.
I just want to inform you that there are still some "hiccups" with the LSP.

**Comment by dibarbet** [comment]
> It looks like the Intellisense issue is resolved in v2.39.29, although it still switches between random TFM contexts, when VSCode is restarted, which you can see when hitting F12 - Go to definition.

Great that the original issue is resolved - the TFM switching issue should hopefully improve soon, we're actively working on adding the ability to change the active document TFM.  In 2.39.29 we started showing the active TFM in the language status bar (which you can pin so it always shows instead of clicking on it)
![image](https://github.com/user-attachments/assets/432bb3ea-9324-4162-aeef-48a9720a746e)



> Also the restart of .NET Language Server still shows the same error as initially described.

Yup, that is not fixed yet, and hasn't reached the top of the priority list since there is a workaround (reload window).

**Comment by matherm-aboehm** [comment]
Thank you for the hint, this was easy to miss.
