### ISSUE TITLE
Read this for fix: Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server

### ISSUE THREAD

**Issue by webreidi** [microsoft/vscode-dotnettools#1892]
Referenced issue: https://github.com/dotnet/vscode-csharp/issues/8034

If you are experiencing this issue, please ensure you are on the latest version of the .NET Install Tool extension, v2.3.1 or greater.

**Comment by arunchndr** [comment]
This is fixed on latest release.

**Comment by markheath** [comment]
hi @arunchndr, which latest release are you referring to? I am still having this problem but seem to be fully up to date on everything (VS Code 1.99.2, C# extension 2.72.27, .NET Install tool 2.3.2, C# Dev Kit extension 1.18.23, and .NET 9 SDK 9.0.203)

**Comment by arunchndr** [comment]
@markheath the latest C# extension version has the fix. We released one more hotfix you could try at 2.74.24. If that does not fix your scenarios, we may need to open a new issue to track yours.

**Comment by markheath** [comment]
Thanks, I enabled pre-release for the C# extension and tried with 2.74.24 but unfortunately, have exactly the same issue:

```
2025-04-16 09:15:51.424 [info] Locating .NET runtime version 9.0.1
2025-04-16 09:16:01.376 [info] Dotnet path: C:\Program Files\dotnet\dotnet.exe
2025-04-16 09:16:01.376 [info] Activating C# + C# Dev Kit...
2025-04-16 09:16:03.516 [info] [stdout] {"pipeName":"\\\\.\\pipe\\8d99b013"}

2025-04-16 09:16:03.517 [info] received named pipe information from server
2025-04-16 09:16:03.519 [info] [Error - 9:16:03 AM] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
2025-04-16 09:16:03.519 [info] Error: connect EPERM \\.\pipe\8d99b013
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1611:16)
```

Please let me know if you want me to open a new issue to track this. I would like to get this resolved, as I have been unable to use VS Code for C# dev for some time now.

**Comment by markheath** [comment]
I still have this problem. However, I have at least discovered that running VS Code in Administrator works (although is very frustrating to do on my work PC as it means I have to give privilege elevation justifications for every process it starts which there are about 15 of). And a couple of co-workers have the same issue, so I am assuming it might be to do with our corporate IT security policy.

Is there a way of knowing whether it can't connect because the language server isn't running, or because something is blocking the named pipe connection? I'm assuming the latter because I can see a process running Microsoft.CodeAnalysis.LanguageServer.exe in my Task Manager.

**Comment by markheath** [comment]
Finally have this resolved - was something in our internal IT security policy (BeyondTrust) blocking the named pipe connection
