### ISSUE TITLE
[BUG] Launch fails if extension is installed in readonly filesystem

### ISSUE THREAD

**Issue by GGG-KILLER** [microsoft/vscode-dotnettools#448]
### Describe the Issue

If the extension is installed in a read-only FS (as happens in NixOS), the launch fails for 2 reasons:
1. The cache directory is set up in the extension directory (which is read-only);
2. The extension attempts to chmod the binaries (which are read-only).

I have implemented [a fix](https://github.com/GGG-KILLER/nixos-configs/blob/1fb658e12e16ea2479722231efb9e4b6a66069bc/common/overlays/local/ms-dotnettools.csdevkit/default.nix#L68-L72) in the build script for my installation however this would be best solved upstream.

### Steps To Reproduce

1. Install a Linux distro where .NET is installed in a read-only FS (e.g. NixOS)
2. Install the extension (and patch the binaries if you're on NixOS)
3. Have the extension fail with "unable to chmod files" and "unable to set up cache directory"

### Expected Behavior

Extension detects it is in a read-only FS and makes the appropriate adjustments.

### Environment Information

- OS: NixOS 23.11.20230825.5690c42
- VSCode Version: 1.81.1
- Extension Version: 0.4.6

**Comment by AArnott** [comment]
Thanks for reporting this, @GGG-KILLER. I've never heard of VS Code extensions being installed on a read-only file system before. How is it that the extension gets installed if the file system is readonly? Assuming the file system is read/write at that point, when does it become readonly? Is there some reason that transition has to happen between installing the extension and using it for the first time?

**Comment by AArnott** [comment]
@lifengl The reason we didn't go with `globalStoragePath` is because it's shared with other versions of the extension, and the cache we keep is version-specific. Using global storage under a version-specific path would leave a trail of old files behind, or we could delete the other version'd directories at the risk of blowing away cache used by another VS Code profile/installation.

And it wouldn't solve the chmod problem, which can only be solved by packing the VSIX from a non-Windows build agent.

**Comment by GGG-KILLER** [comment]
> Thanks for reporting this, @GGG-KILLER. I've never heard of VS Code extensions being installed on a read-only file system before. How is it that the extension gets installed if the file system is readonly? Assuming the file system is read/write at that point, when does it become readonly? Is there some reason that transition has to happen between installing the extension and using it for the first time?

The extensions are in a read-only FS because every single package in NixOS is installed in a read-only FS located in `/nix/store`, and the way they get installed is that they get processed by a build script (where we also patch the ELF files in NixOS as the ELF interpreter, ICU and other libraries are in non-standard locations) and then moved to a folder in `/nix/store` where everything is stored in a path based on the hash of the inputs for the package build.

The point of everything being immutable is that multiple references to any package can reference the same place and the package is guaranteed to not change so the hash always matches (which enables global caching and reuse).

You can see the build "script" here: https://github.com/GGG-KILLER/nixos-configs/blob/fcea8d8a5bd4bfed8bd6f9fbd1724d26b1f574b4/common/overlays/local/ms-dotnettools.csdevkit/default.nix

**Comment by AArnott** [comment]
That's a neat idea. I wonder how much disk space it saves and how its approach compares to de-duplicating file systems. 

As I mentioned above, we have a couple unique challenges to overcome before we can be 'read only file system compliant'. We can leave the issue active till we work both of those out. I don't think it's going to be fixed right away, but knowing this is a 'north star' to reach for will help us avoid increasing our dependency on writing to the extension directory, and eventually I think we can get to where you want.

**Comment by GGG-KILLER** [comment]
> That's a neat idea. I wonder how much disk space it saves and how its approach compares to de-duplicating file systems.

It actually saves quite a bit of space if you enable hardlinking deduplication:
```console
ggg@sora$ sudo nix-collect-garbage -d
[sudo] password for ggg: 
removing old generations of profile /nix/var/nix/profiles/system
removing old generations of profile /nix/var/nix/profiles/per-user/root/channels
removing old generations of profile /nix/var/nix/profiles/per-user/ggg/profile
removing old generations of profile /nix/var/nix/profiles/default
removing old generations of profile /nix/var/nix/profiles/per-user/root/channels
finding garbage collector roots...
deleting garbage...
deleting unused links...
note: currently hard linking saves 69463.02 MiB
0 store paths deleted, 0.00 MiB freed
```

> As I mentioned above, we have a couple unique challenges to overcome before we can be 'read only file system compliant'. We can leave the issue active till we work both of those out. I don't think it's going to be fixed right away, but knowing this is a 'north star' to reach for will help us avoid increasing our dependency on writing to the extension directory, and eventually I think we can get to where you want.

Yeah, I didn't (nor would it be fair to) expect an instant solution (even more so since this *is* an edge case after all), it's just a long term wish that we can remove the "hack" of patching a minified file and instead have support directly in the extension itself which would be way more reliable 😅.

**Comment by thomaslaich** [comment]
I'm having the same issue, and was so far installing the csharp extensions directly via marketplace and not via nix (which works fine on my nix-darwin machine, but not on my NixOS).

@GGG-KILLER I tried to copy your code here today:

https://github.com/GGG-KILLER/nixos-configs/tree/master/packages/ms-dotnettools.csharp

it works great for .NET 8.x projects, thanks a lot! (something is still broken on .NET 9 projects somehow :( )

Would you maybe be so kind and make a separate overlays (or package) repo for the C# extensions? This way I (and surely others) could just use an overlay in my system flake. Of course, I get it if you don't want to do it or don't have the time! Otherwise, I will pretty much resort to copying your code :)

**Comment by GGG-KILLER** [comment]
@thomaslaich the code in my repo is just so I can use the prerelease version and dogfeed changes before upstreaming to nixpkgs, you can instead use `pkgs.vscode-extensions.ms-dotnettools.csharp`.

It should be working fine if you use `sdk-9_0-bin` instead of `sdk_9_0`.

**Comment by thomaslaich** [comment]
Oh, I see. I was using the extension from https://github.com/nix-community/nix-vscode-extensions . That extension will always try to create a `cache` directory inside the extension directory (as described in the issue here). Didn't realize you fixed this upstream directly in nixpkgs, thanks!

However, if I use the newest sdk (even the `-bin` version, and both 8.0.406 and 9.0.200), i get this error:

C# extension
```
[info] [stdout] fail: Microsoft.CodeAnalysis.LanguageServer.ExportProviderBuilder[0]
      Failed to save MEF cache: System.UnauthorizedAccessException: Access to the path '/nix/store/gcsyyb0jxvpr16bq21669fw2gzc14ykx-vscode-extension-ms-dotnettools-csharp-2.63.32/share/vscode/extensions/ms-dotnettools.csharp/.roslyn/cache' is denied.
       ---> System.IO.IOException: Permission denied
         --- End of inner exception stack trace ---
         at System.IO.FileSystem.CreateParentsAndDirectory(String fullPath, UnixFileMode unixCreateMode)
         at System.IO.FileSystem.CreateDirectory(String fullPath, UnixFileMode unixCreateMode)
         at System.IO.Directory.CreateDirectory(String path)
         at Microsoft.CodeAnalysis.LanguageServer.ExportProviderBuilder.WriteCompositionCacheAsync(String compositionCacheFile, CompositionConfiguration config, ILogger logger) in /_/src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/ExportProviderBuilder.cs:line 162
```

.NET install tool:

```
Error : (DotnetNotInstallRelatedCommandFailed)
Failed to download .NET undefined:
EACCES: permission denied, open '/nix/store/j7hr1ji5xzx972i5zfmsxf8nnwzr9ax1-vscode-extension-ms-dotnettools-vscode-dotnet-runtime-2.2.8/share/vscode/extensions/ms-dotnettools.vscode-dotnet-runtime/dist/installed.lock'
```

the first error is probably this issue here:

https://github.com/dotnet/roslyn/issues/76892

Sorry for spamming this thread. this probably gets pretty off topic.

**Comment by GGG-KILLER** [comment]
> C# extension
> ```
> [info] [stdout] fail: Microsoft.CodeAnalysis.LanguageServer.ExportProviderBuilder[0]
>       Failed to save MEF cache: System.UnauthorizedAccessException: Access to the path '/nix/store/gcsyyb0jxvpr16bq21669fw2gzc14ykx-vscode-extension-ms-dotnettools-csharp-2.63.32/share/vscode/extensions/ms-dotnettools.csharp/.roslyn/cache' is denied.
>        ---> System.IO.IOException: Permission denied
>          --- End of inner exception stack trace ---
>          at System.IO.FileSystem.CreateParentsAndDirectory(String fullPath, UnixFileMode unixCreateMode)
>          at System.IO.FileSystem.CreateDirectory(String fullPath, UnixFileMode unixCreateMode)
>          at System.IO.Directory.CreateDirectory(String path)
>          at Microsoft.CodeAnalysis.LanguageServer.ExportProviderBuilder.WriteCompositionCacheAsync(String compositionCacheFile, CompositionConfiguration config, ILogger logger) in /_/src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/ExportProviderBuilder.cs:line 162
> ```

This does indeed happen, but that doesn't prevent the extension from working. Worst case it'll make the startup slower but won't actually affect its functionality.

> .NET install tool:
> 
> ```
> Error : (DotnetNotInstallRelatedCommandFailed)
> Failed to download .NET undefined:
> EACCES: permission denied, open '/nix/store/j7hr1ji5xzx972i5zfmsxf8nnwzr9ax1-vscode-extension-ms-dotnettools-vscode-dotnet-runtime-2.2.8/share/vscode/extensions/ms-dotnettools.vscode-dotnet-runtime/dist/installed.lock'
> ```

There is an option on the .NET Install Tool extension to tell it to use the already installed SDK: `dotnetAcquisitionExtension.sharedExistingDotnetPath` which you can add to your home-manager config or just point to the `dotnet` executable manually (if you want to avoid having to constantly change it on every update, I recommend pointing it to the symlink for the current generation).

For more settings you can check the extension's readme: https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.vscode-dotnet-runtime

**Comment by thomaslaich** [comment]
thanks for your help.

For some reason i had this setting activated:
```
"dotnet.workingWithTestSignedSdk" = true;
```
removing it made it work for some reason.

Does the .NET install tool check the envvar `$DOTNET_ROOT`? because i'm setting that in all my devshells.

Either way, my extension now works, thanks :)
