### ISSUE TITLE
[BUG] override methods insertion fails for Unity projects

### ISSUE THREAD

**Issue by mikael-bergstrom-ntisthlm** [microsoft/vscode-dotnettools#482]
### Describe the Issue

When using this plugin, code completion for overriding abstract/virtual methods does not work. In fact, it seems like the plugin actively sabotages any attempt at overriding methods.

This problem only appears (for me) specifically when working on Unity projects, no normal C# projects seem to be affected.

All attempts at using suggested autocompletes for an override, or just writing out the whole thing manually, is just auto-replaced either with an empty string or a single character.

So if I write "public override void ToString()" manually, it results in "public override void T" and nothing else.
If I write "public override" and choose ToString from the suggestions dropdown, I just get nothing.

I'm at the end of my rope here. very open to suggestions.

![Code_thAMOoIyyf](https://github.com/microsoft/vscode-dotnettools/assets/54838303/248f4f4e-3521-4346-8ed4-b749fd0063f7)

### Steps To Reproduce

1. Create a new project.
2. Remove "Engineering" metapackage from project, as it forces old version of Visual Studio Editor package for some reason.
3. Install latest Visual Studio Code Editor package into project.
4. Make sure VS Code is selected as external script editor.
5. Create new C# Script in Unity project.
6. Open C# script by doubleclicking in Unity.
7. In the class, try to write "public override void ToString() {}".
8. You will probably not be able to.

### Expected Behavior

When selecting ToString from suggestion list, "ToString()" should be added to the code.
When writing "public override void ToString()" out manually, it shouldn't… disappear.

### Environment Information

Windows 11 23H2
Unity 2022.3.8f1 + Visual Studio Editor package 2.0.20
Visual Studio Code 1.81.1 + C# dev kit 0.4.10 + Unity extension 0.9.0

**Comment by jbevain** [comment]
Hi @mikael-bergstrom-ntisthlm,

Thanks for reaching out. Now that's curious.

I don't reproduce on my Unity test projects.

Which version of Unity are you using?
Can you reproduce in a new empty Unity project? (If not, it might be triggered by a Unity package)

**Comment by mikael-bergstrom-ntisthlm** [comment]
@jbevain  Unity 2022.3.8f1, seems like it's happening in all my new (and old) projects.

I tried this in a VM (Windows 11, Hyper-V):
- Installed Unity Hub & Unity 2022.3.8f1 using winget
- Installed VS Code 1.81.1 using winget
- Added only the Unity, C# and C# Dev Kit extensions to Code
- Created a brand new 3D project in Unity
- Removed the "Engineering" metapackage from the project, manually added only the Visual Studio Editor package from the Unity registry
- Created a new C# Script called "OverrideTesting" in the Unity assets for the prohect. Double-clicked.
- Waited for the C# Dev Kit to kick in and find the project.
- Tried overriding ToString as above

Result: Same bug. And that's with a clean windows install & a VS Code with no extensions beyond the absolute bare necessities.

I made a github repo with my (empty) project just in case something in it might be useful; it's public on my profile, named "BrokenOverrides" (Sounds like a weird cyberpunk game maybe).

I'd love to help pinning down the cause of this, so please let me know if there's anything I can test or look into in order to figure out what's happening.

I might try this on a different machine later, running windows 10, to see if that changes anything. But it really shouldn't, other non-Unity projects work fine.

**Comment by jbevain** [comment]
@mikael-bergstrom-ntisthlm thanks Mikael, what's the version of the `C#` extension?

Does it happen if you switch the `C# Dev Kit` extension to pre-release? (I'm running `v0.5.2`).

**Comment by mikael-bergstrom-ntisthlm** [comment]
@jbevain C# extension v2.0.436

I've now switched to C# Dev Kit 0.5.2 (from 0.4.10). No change, I still get the bug.

**Comment by taanhtuan** [comment]
I faced same issue, here are my settings:
- Unity 2022.3.6
- C# Dev Kit 0.4.10
- C# Dev Kit Pre-Release 0.5.2

**Comment by mikael-bergstrom-ntisthlm** [comment]
I have now tested this (Same versions of Unity, VS Code, extensions & packages) on a physical Win10 machine as well. Same problem.

I have also tried Unity 2023.1.11f1 now. And VS Code Insiders (Version: 1.82.0-insider).

I have also tried disabling C# Dev Kit and Unity extensions in VS Code. Turns out they don't matter. Also tried making my own non-MonoBehavior class. Turns out VS Code's C# extension just doesn't like it when projects are created by Unity I guess.

But when I create or open a normal C# Console App project… everything works fine.

This is getting a bit weird.

**Comment by jbevain** [comment]
@mikael-bergstrom-ntisthlm thanks, we really appreciate your help trying to pin this down! We also think the issue is in the `C#` extension, we'll be working with the Roslyn folks trying to understand what is happening.

**Comment by jbevain** [comment]
@mikael-bergstrom-ntisthlm ok I can reproduce on Windows. I'll create a repro for our compiler team and we'll see what they make of it. Thanks again.

**Comment by tmeschter** [comment]
Tagging as "area-project" because it sounds like references aren't making it through to the Language Service.

**Comment by tmeschter** [comment]
The completion list behavior was made more resilient to missing reference information in https://github.com/dotnet/roslyn/pull/69795. However, I haven't been able to reproduce the missing reference issue on the latest builds of C# and C# Dev Kit using @jbevain's repro project. It is entirely possible that it was fixed by some other fix in the Project System or even in runtime discovery. 🤷🏻‍♂️

I'm going to close this issue as everything now appears to be working as expected.

**Comment by mikael-bergstrom-ntisthlm** [comment]
The bug still exists for me, but I guess it takes a while for whatever the solution turned out to be to percolate down to my level =) (I'm on C# extension 2.1.2, C# Dev Kit 0.5.24 now). I'll keep an eye out!

**Comment by Pookay** [comment]
Hi !
Same issue for me. I was searching a post like this one with the error message out of vscode's console. So here the message I get when trying to autocomplete when overriding methods (C# + Unity of course).
```txt
[error] Failed to make a complex text edit for completion.: Error: Failed to make a complex text edit for completion.
	at r.h (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:107:83091
```

**Comment by mikael-bergstrom-ntisthlm** [comment]
Can confirm, C#ext 2.3.27, devkit 0.5.98 fixed it for me.

Thanks for fixing this! Great work!
