### ISSUE TITLE
[BUG] C# Dev Kit v1.0.14 - Sign in with Microsoft only possible with work or school accounts - why???

### ISSUE THREAD

**Issue by Twoleeland** [microsoft/vscode-dotnettools#697]
### Describe the Issue

When installing "C# Dev Kit v1.0.14" you are forced to sign in with Microsoft work or school account. Using private Microsoft accounts is not possible, but why?!?!

And the account icon in VS Code shows always "1". Either enable login with Microsoft private accounts or add possibility to disable "sign in request"!!!

<img width="266" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/1656150/34c73fd2-1a96-457f-b74d-daadff6879ff">

Thanks in advance!

### Environment Information

Windows 11 22H2/23H2 Pro
VS Code 1.84.1 (latest official update)

**Comment by timheuer** [comment]
@Twoleeland Can you confirm any errors you are seeing? I use my personal Microsoft account and am able to login successfully using my non-work/school account.

**Comment by EdiWang** [comment]
I had the same issue yesterday with 2 of my PCs.

![image](https://github.com/microsoft/vscode-dotnettools/assets/3304703/a79c8e13-a632-450d-926a-0407694ff590)

This morning after VSCode update to v1.84.2, the problem is gone. C# Dev Kit does not requires me to sign in any more, seems working with my MSA.

I can also see it's a trusted extension under my personal account.

![image](https://github.com/microsoft/vscode-dotnettools/assets/3304703/318c0b79-22e2-4f19-8f01-a4e755d6079f)

![image](https://github.com/microsoft/vscode-dotnettools/assets/3304703/3328177a-a8ad-49ad-942f-1b2cac0ac7c7)

If there is no code change from the extension itself. It may be a mis-config on the Azure Entra ID application registration side.

Anyway, it's working for me now. If it happens again, I'll try to put more details to this thread.

**Comment by timheuer** [comment]
@Twoleeland wondering if you can update VSCode as well and see if resolves.  We're still investigating but might be something in a shared credential manager with MSA.

**Comment by Twoleeland** [comment]
My problem was the same which @EdiWang already explained in detail. 😉

One day later the problem was gone. Don't know what MS had done in the background, but login wasn't restricted to school or work accounts anymore for me.

**Comment by darkguy2008** [comment]
I have just encountered the same issue today. Did something change?

Also, happy new year 🥳 !

**Comment by fbgrigolo** [comment]
I'm having the same issue, I've already tried reinstalling the extension and checking for updates and nothing has changed.

**Comment by darkguy2008** [comment]
> I'm having the same issue, I've already tried reinstalling the extension and checking for updates and nothing has changed.

I had the same issue a couple days ago. The solution is just to reinstall the extension.

**Comment by fbgrigolo** [comment]
> > I'm having the same issue, I've already tried reinstalling the extension and checking for updates and nothing has changed.
> 
> I had the same issue a couple days ago. The solution is just to reinstall the extension.

I'll try this again, if it doesn't work I'll report back here in the issue again

**Comment by darkguy2008** [comment]
> > > I'm having the same issue, I've already tried reinstalling the extension and checking for updates and nothing has changed.
> > 
> > 
> > I had the same issue a couple days ago. The solution is just to reinstall the extension.
> 
> I'll try this again, if it doesn't work I'll report back here in the issue again

Well F me, the error is back and reinstalling it doesn't work.

@timheuer this issue seems to be recurring, any way it can be reopened?

**Comment by vchirikov** [comment]
Same, reinstall to `v1.4.2 (pre-release)` doesn't help and sign-in/sign-out doesn't either.

**Comment by incomingstick** [comment]
I am running into this issue as well, on Linux

VSCode version 1.86.2
Extension version v1.3.10 (and pre-release v1.4.2) 

A **very brief** workaround is to navigate to the Account dropdown (person icon) > Select the Microsoft Account > "Manage Trusted Extensions" > un-check C# Dev Kit > Click Ok > Re-launch VSCode

 It should prompt you to grant permissions to C# using that account, instead of logging in. This will only work for that current session, and resets when you close VSCode again.

In the C# Dev Kit Output, this appears to be the error:
```
IdeBenefitsSource: Failed to fetch entitlements. Error: 'Error: Request to https://api.subscriptions.visualstudio.microsoft.com/Me/Entitlements/IDEBenefits?api-version=2023-03-26&caller=vscode failed with status code: 401 and response ""'
```

**Comment by AndreyTretyak** [comment]
Thanks to those that have reported this and to those providing us traces, that helped track down an area to investigate and we’re working on a fix.

**Comment by friflo** [comment]
> This will only work for that current session, and resets when you close VSCode again.

Can confirm this.

**Comment by GillisMcDonald** [comment]
Doesn't work for me with version 1.4.6 or 1.3.10. Reinstalling also doesn't change anything.

**Comment by incomingstick** [comment]
I'd like to follow up about my "Solution". It will only make the notification disappear. The error I provided will still occur when you approve access, but is otherwise a silent failure using that "workaround".

**Comment by fmotion1** [comment]
Having this problem as well ... really hoping there is a fix soon.

**Comment by JunRamoneda** [comment]
Encountering the same issue with required organization sign-in. Running VS Code 1.86.2 on ubuntu 22.04

**Comment by Juansero29** [comment]
Same problem too, this needs a fix please

**Comment by dusda** [comment]
The workaround @Juansero29 detailed does not work for me.

C# Dev Kit Extension v1.3.10 or 1.2.7
VS Code 1.86.2
Windows 11 10.0.22621 Build 22621

**Comment by thejonan** [comment]
Problem still here!

**Comment by Juansero29** [comment]
> The workaround @Juansero29 detailed does not work for me.
> 
> C# Dev Kit Extension v1.3.10 or 1.2.7 VS Code 1.86.2 Windows 11 10.0.22621 Build 22621

I updated the steps, had forgot an important step at the end

**Comment by Cronkan** [comment]
Seems to be some error in the scope provided when logging in (replaced guids with empty guid for security)

It adds `00000000-0000-0000-0000-000000000000/.default` which isn't a valid scope
Removing it from the url when logging in makes the login work, but it still throws error in Microsoft Authentication

```Attempted to get a new session using the existing session with scopes '00000000-0000-0000-0000-000000000000/.default VSCODE_CLIENT_ID:00000000-0000-0000-0000-000000000000/.default VSCODE_TENANT:common email offline_access openid profile' but it failed due to: {"error":"invalid_scope","error_description":"AADSTS70011: The provided value for the input parameter 'scope' is not valid. The scope '00000000-0000-0000-0000-000000000000/.default email offline_access openid profile' does not exist. Trace ID: 00000000-0000-0000-0000-000000000000 Correlation ID: 00000000-0000-0000-0000-000000000000Timestamp: 2024-02-26 14:28:51Z","error_codes":[70011],"timestamp":"2024-02-26 14:28:51Z","trace_id":"00000000-0000-0000-0000-000000000000","correlation_id":"00000000-0000-0000-0000-000000000000"}```

**Comment by ddiatlov** [comment]
Still experiencing the error. the workarounds don't work.

**Comment by Rich-Hopkins** [comment]
Same here. Still a problem and the only thing that works for me is @Juansero29's solution, but like he states, that is lost when restarting Code.

**Comment by incomingstick** [comment]
> I'd like to follow up about my "Solution". It will only make the notification disappear. The error I provided will still occur, and is visible in the C# Dev Kit output, when you approve access, but is otherwise a silent failure.

Thank you @Juansero29 for putting my "solution" into more clear steps. I wanted to follow up again and make sure people saw my other note. It is true that, even after going through those steps, nothing will actually be fixed. That is because the error I mentioned in my original post will still occur; my solution simply just makes the notification go away for that session. The error that occurs can be found in the C# Dev Kit Output.

Everyone, It would be helpful to the devs if you could note whether you see that same error, beyond just confirming you are also having this issue. The error is:

> In the C# Dev Kit Output, this appears to be the error:
> 
> ```
> IdeBenefitsSource: Failed to fetch entitlements. Error: 'Error: Request to https://api.subscriptions.visualstudio.microsoft.com/Me/Entitlements/IDEBenefits?api-version=2023-03-26&caller=vscode failed with status code: 401 and response ""'
> ```

**Comment by cobrabr** [comment]
I'm seeing that exact same error on my VS Code.

**Comment by speedhawk21** [comment]
Still getting the same error:

Name: C# Dev Kit
Id: ms-dotnettools.csdevkit
Description: Official C# extension from Microsoft
Version: 1.3.10
Publisher: Microsoft

VSCode Version: 1.86.2
Commit: 903b1e9d8990623e3d7da1df3d33db3e42d80eda
Date: 2024-02-13T19:42:13.651Z (1 wk ago)
Electron: 27.2.3
ElectronBuildId: 26908389
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin x64 23.3.0

IdeBenefitsSource: Failed to fetch entitlements. Error: 'Error: Request to https://api.subscriptions.visualstudio.microsoft.com/Me/Entitlements/IDEBenefits?api-version=2023-03-26&caller=vscode failed with status code: 401 and response ""'

**Comment by incomingstick** [comment]
This appears to have been resolved alongside the latest VSCode February update (v1.87.0).

**Comment by jrdodds** [comment]
> This appears to have been resolved alongside the latest VSCode February update (v1.87.0).

I'm no longer seeing the issue today as well (and that was prior to applying the v1.87.0 update).

**Comment by Dymerz** [comment]
I still encounter the problem. While the workaround works for me, it needs to be re-executed if you close VS Code in any way.
Attempting to `Sign in with Microsoft to use C# Dev Kit` still requires a `work or school account`.


```
Version: 1.87.0 (user setup)
Commit: 019f4d1419fbc8219a181fab7892ebccf7ee29a2
Date: 2024-02-27T23:41:44.469Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22631
```

Output:
```
IdeBenefitsSource: Failed to fetch entitlements. Error: 'Error: Request to https://api.subscriptions.visualstudio.microsoft.com/Me/Entitlements/IDEBenefits?api-version=2023-03-26&caller=vscode failed with status code: 500 and response "{"type":"https://tools.ietf.org/html/rfc7231#section-6.6.1","title":"An error occurred while processing your request.","status":500,"traceId":"00-a73c7829c012a2e2d9abd41922c5d9c5-9fe78ff21c2115d8-00"}"'
```

**Comment by alexrp** [comment]
Still occurs for me. For what it's worth, this has only started happening in the last couple of weeks for me. Before that, my personal account worked fine.

**Comment by GillisMcDonald** [comment]
The notification went away for a few days but its back again :( Login still says I cant sign in with a personal account.

**Comment by Abdullah7-bit** [comment]
Last day my VS code got corrupted and when I re-install VS code, it automatically detects the previous configuration of extensions and when I used VS code the C# Devkit login notification did not pop up since then. I have C# devkit -v: 1.3.10 and VS code -v: 1.87.0 ..... So is this issue resolve for everyone or is it just a temporarily went away on my local machine?

**Comment by Dymerz** [comment]
I didn't do anything special, and it seems to be resolved. 🚀

The `Sign in with Microsoft to use C# Dev Kit` no longer requires a `work or school account` and there are no more `403/500` errors in the extension output.

**Comment by AndreyTretyak** [comment]
We've shipped the fix for this issue in 1.4.28. Please let us know if you are still facing C# Dev Kit requiring work or school account after update.

**Comment by GillisMcDonald** [comment]
I am still facing C# Dev Kit requiring work or school account after update.

**Comment by AndreyTretyak** [comment]
@GillisMcDonald could you please check what version of C# Dev Kit are you using? 
You can do that navigating to extension page in VS Code.
![image](https://github.com/microsoft/vscode-dotnettools/assets/2550113/8e0c5750-7089-4ab1-bdc9-52522c415874)
So far fix shipped only in pre-release verision (v1.4.38) if you happen to been using release version (v1.3.10) switching to pre-release (button on the same page) migth be able to resolve problem.

**Comment by GillisMcDonald** [comment]
> @GillisMcDonald could you please check what version of C# Dev Kit are you using? You can do that navigating to extension page in VS Code. ![image](https://private-user-images.githubusercontent.com/2550113/311402451-8e0c5750-7089-4ab1-bdc9-52522c415874.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5NDc3NDMsIm5iZiI6MTcwOTk0NzQ0MywicGF0aCI6Ii8yNTUwMTEzLzMxMTQwMjQ1MS04ZTBjNTc1MC03MDg5LTRhYjEtYmRjOS01MjUyMmM0MTU4NzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDlUMDEyNDAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjljNmRkZDI5OTAyY2Q2ZGE5OGZiMzBmOTc0OWI4MjM4M2Q1NjFmZTczZjUyNThjYmFiZjBiZmY5NDA1ODE1YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.xWkI4ECVuNtzu3cBWeyRvUBuPIpmBli9DnydwAmpMnA) So far fix shipped only in pre-release verision (v1.4.38) if you happen to been using release version (v1.3.10) switching to pre-release (button on the same page) migth be able to resolve problem.

I am using version 1.3.10. However the error has disappeared as of today. It appears to be very inconsistent.

**Comment by AndreyTretyak** [comment]
Version with the fix moved to release channel, so I'll close the issue. 
Please let us know if you'll see this problem in the extension after version 1.4.38.

**Comment by iJungleboy** [comment]
I kind of have the same issue again, and I think it's tracked on this issue https://github.com/microsoft/vscode-dotnettools/issues/1151

**Comment by gakusei25** [comment]
This is a current issue in the latest version of VSC.

**Comment by gakusei25** [comment]
This is a current issue in the latest version of VSC.

**Comment by AndreyTretyak** [comment]
@gakusei25 are you forced to sign in with work or school account in the latest version of VSC?
Could you please share url that VSC opens in browser when you are trying to sign in? (the one that shows MS Sign In page)

**Comment by PetrKnedlik** [comment]
why is it still happening? That notification is bugging me and I can't get rid of it 😠

**Comment by DickHorner** [comment]
well, it just happened to me first time ever, I'm on github pro as an educator.

**Comment by machooth** [comment]
Issue still happening on vscode 1.109.5, both with the release and the pre-release version of the C# dev kit.
