### ISSUE TITLE
[BUG] C# Dev Kit ignore global.json for build and test

### ISSUE THREAD

**Issue by thegrahamking** [microsoft/vscode-dotnettools#791]
### Describe the Issue

I had .NET 6 and 7 SDK installed 

```
> dotnet --list-sdks
2.1.818 [C:\Program Files\dotnet\sdk]
2.2.207 [C:\Program Files\dotnet\sdk]
3.0.103 [C:\Program Files\dotnet\sdk]
3.1.426 [C:\Program Files\dotnet\sdk]
5.0.102 [C:\Program Files\dotnet\sdk]
5.0.301 [C:\Program Files\dotnet\sdk]
5.0.408 [C:\Program Files\dotnet\sdk]
6.0.101 [C:\Program Files\dotnet\sdk]
6.0.116 [C:\Program Files\dotnet\sdk]
6.0.202 [C:\Program Files\dotnet\sdk]
6.0.203 [C:\Program Files\dotnet\sdk]
6.0.311 [C:\Program Files\dotnet\sdk]
6.0.417 [C:\Program Files\dotnet\sdk]
7.0.203 [C:\Program Files\dotnet\sdk]
7.0.305 [C:\Program Files\dotnet\sdk]
7.0.404 [C:\Program Files\dotnet\sdk]
```

My solution uses .NET 6 SDK via `global.json`
``` json
{
  "sdk": {
    "version": "6.0.101"
  }
}
```
My project targets .NET 6 (`.csproj`)
```
    <TargetFramework>net6.0</TargetFramework>
```
and has all code analyzers enabled  (`.csproj`)
```
    <AnalysisLevel>latest-all</AnalysisLevel>
```
and treats warnings as errors  (`.csproj`)
```
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
```

Both the `.NET: Build` task in vscode 
``` json
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "dotnet",
			"task": "build",
			"group": {
				"kind": "build",
				"isDefault": true
			},
			"problemMatcher": [
				"$msCompile"
			],
			"label": "dotnet: build"
		}
	]
}
```
and `dotnet build` from the solution root ran fine, and produced no analyzer errors.

Once I installed the .NET 8 SDK, and restarted my machine,
```
> dotnet --list-sdks
2.1.818 [C:\Program Files\dotnet\sdk]
2.2.207 [C:\Program Files\dotnet\sdk]
3.0.103 [C:\Program Files\dotnet\sdk]
3.1.426 [C:\Program Files\dotnet\sdk]
5.0.102 [C:\Program Files\dotnet\sdk]
5.0.301 [C:\Program Files\dotnet\sdk]
5.0.408 [C:\Program Files\dotnet\sdk]
6.0.101 [C:\Program Files\dotnet\sdk]
6.0.116 [C:\Program Files\dotnet\sdk]
6.0.202 [C:\Program Files\dotnet\sdk]
6.0.203 [C:\Program Files\dotnet\sdk]
6.0.311 [C:\Program Files\dotnet\sdk]
6.0.417 [C:\Program Files\dotnet\sdk]
7.0.203 [C:\Program Files\dotnet\sdk]
7.0.305 [C:\Program Files\dotnet\sdk]
7.0.404 [C:\Program Files\dotnet\sdk]
8.0.100 [C:\Program Files\dotnet\sdk]
```
`dotnet build` continue to work the same, no errors
```
> dotnet build
Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  ClassLibrary1 -> C:\src\temp\vscode-dotnet-sdk-test\ClassLibrary1\bin\Debug\net6.0\ClassLibrary1.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.57
```

However, vscode starting seeing errors from the [new analyzers added in .NET 8](https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-8#code-analysis), and, therefore, failing the build.

```
 *  Executing task: dotnet: build 

dotnet build C:\src\temp\vscode-dotnet-sdk-test\ClassLibrary1.sln /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary 
MSBuild version 17.8.3+195e7f5a3 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
C:\src\temp\vscode-dotnet-sdk-test\ClassLibrary1\Class1.cs(9,9): error CA1510: Use 'ArgumentNullException.ThrowIfNull' instead of explicitly throwing a new exception instance (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1510) [C:\src\temp\vscode-dotnet-sdk-test\ClassLibrary1\ClassLibrary1.csproj]

 *  The terminal process terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 
```
Note CA1510 code analyzer was introduced in .NET 8.

I also spotted that the MSBuild version used by `dotnet build`, `17.0.0+c9eb9dd64` corresponds to that of .NET 6 according to [the docs](https://learn.microsoft.com/en-us/dotnet/core/porting/versioning-sdk-msbuild-vs#lifecycle) but the version used by vscode corresponds to .NET 8, `17.8.3+195e7f5a3`.

In addition,although this is not blocking or an issue for me, but may be related, if you look in the C# Dev Kit - Test Explorer you can see that .NET 8 SDK is being used (line 2)
```
Created Test Controller
Using vstest from dotnet sdk in [C:\Program Files\dotnet\sdk\8.0.100].
Initialized Test Explorer Server [27324]
Test Store Folder: c:\Users\{redacted}\AppData\Roaming\Code\User\workspaceStorage\707f571392e3c7fef86563f191cff4e9\ms-dotnettools.csdevkit
Test data store opened in 0.015 sec.
Initialized project system provider.

```

### Steps To Reproduce

1. Install .NET 6 SDK
2. Install .NET 8 SDK
3. Create a new .NET Project using the Class Libary template in VSCode (".NET New Project")
4. Apply the following updates:

`Class1.cs`
``` csharp
[assembly:CLSCompliant(true)]

namespace ClassLibrary1;

public class Class1
{
    public Class1(string a)
    {
        if (a == null)
        {
            throw new ArgumentNullException(nameof(a));
        }
    }
}
```
`{Project}.csproj`
``` xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AnalysisLevel>latest-all</AnalysisLevel>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>

  </PropertyGroup>

</Project>
```

6. Add `global.json` to the root (same location as sln) with the following content (ensure version exactly matches .NET 6 SDK version, check via `dotnet --list-sdks`
``` json
{
  "sdk": {
    "version": "6.0.100"
  }
}
```
7. In a terminal, in the sln root, run `dotnet build`.  Observe the build succeeds.
8. Restart VSCode (because changes have been made to `global.json`
9. Reopen SLN
10. Run `.NET: Build` task in vscode.
11. Observe that the build fails due to `CA1510`.

### Expected Behavior

Build is run using the SDK version specified in `global.json`, is consistent with `dotnet build` and, therefore, the build succeeds.

### Environment Information

- OS: Windows 11 22H2
- VS Code verison: 1.85.0
- C# Extension version: v2.13.10
- C# Dev Kit Extension version: v1.1.16
- IntelliCode for C# Dev Kit Extension version: v0.1.26

**Comment by christopher-jones-intern-2023** [comment]
I'm not sure how to "upvote" an issue, but I have a very similar problem: when I use C# Dev Kit Test Explorer to run tests on v1.1.16 I get errors because our global.json is being ignored. However, if I install v1.0.14, all tests pass.

`{
  "sdk": {
    "version": "6.0.400",
    "rollForward": "latestPatch"
  }
}`

**Comment by thegrahamking** [comment]
I can partially confirm what @christopher-jones-intern-2023 has said, the issue with build is not present when rolling back to C# Dev Kit 1.0.14, the SDK version, and therefore the MSBuild version, specified in `global.json` is used.
```
 *  Executing task: C:\Program Files\dotnet\dotnet.exe build C:\src\temp\vscode-dotnet-sdk-test\ClassLibrary1.sln /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary 

Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  ClassLibrary1 -> C:\src\temp\vscode-dotnet-sdk-test\ClassLibrary1\bin\Debug\net6.0\ClassLibrary1.dll
 *  Terminal will be reused by tasks, press any key to close it. 
```
However, C# Dev Kit Test Explorer still reports it's using the .NET 8 SDK (although this is still non blocking for me)
```
Created Test Controller
Using vstest from dotnet sdk in [C:\Program Files\dotnet\sdk\8.0.100].
Initialized Test Explorer Server [2224]
Test Store Folder: c:\Users\graking\AppData\Roaming\Code\User\workspaceStorage\707f571392e3c7fef86563f191cff4e9\ms-dotnettools.csdevkit
Test data store opened in 0.020 sec.
Initialized project system provider.

```

**Comment by AbhitejJohn** [comment]
Adding @arkalyanms and @peterwald for the two issues around Analyzers and Test called out here.

**Comment by peterwald** [comment]
Tagging the project system as Test Explorer calls into the project system to kick off a build.

**Comment by AbhitejJohn** [comment]
Tagging @lifengl on the project system team for thoughts

**Comment by lifengl** [comment]
it is likely related to the location of the global.json file. The file should be put in the root of your workspace folder (or any folder above it). If it is inside a project folder inside the workspace, it would not work.

the global.json is picked up based on the working folder where a dotnet command is executed, and as a general rule, the extension executes those commands on the root of the workspace folder, which is very similar if you open a terminal window in vs code.  It is actually not based on the location of any project.

**Comment by thegrahamking** [comment]
I suspect the location of `global.json` is not the issue for the following reason, all listed above but summarised here for brevity:

- `global.json` is in the workspace root and is ignored and builds are run using the default SDK when using C# Dev Kit 1.1.16
- `global.json` is in the workspace root, is detected correctly and builds are run using the SDK specified within it, when using C# Dev Kit 1.0.14
- CLI builds, from the terminal, where the working directory is the same as the workspace root, with `global.json` there, detect `global.json` correctly and run using the SDK specified within in. I would expect C# Dev Kit's detection and use of `global.json` to match the CLI.

**Comment by vnavkal** [comment]
I am seeing this same issue.  I have a `global.json` file at the root of the workspace, containing (among other things)
```json
  "sdk": {
      "version": "6.0.410",
      "rollForward": "latestFeature"
  }
```
In my `.editorconfig` file, I have
```
dotnet_diagnostic.CA1851.severity = warning
```
for a [rule](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/CA1851) that was introduced in .NET 7.  And I have a `Directory.Build.props` file specifying
```xml
<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
```

Because the `global.json` file specifies .NET 6 and the rule was not present in .NET 6, I would expect the rule to have no effect.  But I would expect that upon switching to .NET 7, the rule would cause errors on any violation.

When I run `dotnet build` from the command line, the build finishes with no errors.  And when I build from VS Code with C# Dev Kit 1.0.14, the build also finishes with no errors.  But when I build from VS Code with C# Dev Kit 1.1.16, the build finishes with several errors saying
> Possible multiple enumerations of 'IEnumerable' collection. Consider using an implementation that avoids multiple enumerations. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1851)....

For what it's worth, I have the following .NET SDKs currently installed:
```
> dotnet --list-sdks
6.0.414 [C:\Program Files\dotnet\sdk]
6.0.415 [C:\Program Files\dotnet\sdk]
6.0.417 [C:\Program Files\dotnet\sdk]
7.0.404 [C:\Program Files\dotnet\sdk]
```

**Comment by leidegre** [comment]
I can only concur with what has been said before. I have a `global.json` that specifies the target SDK I want to use.

When I use `dotnet` commands from the command line in my workspace root, it works as I expect, i.e. it picks up the desirable SDK version. If I go into to the C# Dev Kit solution explorer in VS Code and trigger a build, it is using the .NET 8 SDK (which also happens to be installed on my machine).

Here's an example,

When running dotnet build from command line in workspace root

> C:\Program Files\dotnet\sdk\7.0.404\Microsoft.Common.CurrentVersion.targets(2364,5): warning MSB3246: Resolved file has a bad image, no metadata, or is otherwise inaccessible. PE image does not have metadata.

When running the build via the solution explorer in VS Code

> C:\Program Files\dotnet\sdk\8.0.100\Microsoft.Common.CurrentVersion.targets(2382,5): warning MSB3246: Resolved file has a bad image, no metadata, or is otherwise inaccessible. PE image does not have metadata.

In only noticed this because I happen to have that warning in my build and I can see it's referencing different SDK targets file.

**Comment by thegrahamking** [comment]
This behaviour is still present in C# Dev Kit versions `1.2.7` and pre-release `1.3.4` (tested today)

**Comment by thegrahamking** [comment]
This behaviour is still present in C# Dev Kit version `1.3.10` (tested today)

**Comment by alex-bartleynees** [comment]
Have the same issue, quite annoying and would be nice to see a fix. Thanks.

**Comment by lifengl** [comment]
Thanks a lot to report this bug.

That is indeed a regression happened at the end of the last year. We will work on a fix in a later release.

(To put it simple, the build stack was updated to handle error messages better. In that new code, it didn't set working directory correctly.  global.json is resolved based on the CWD of the process, not the location of the solution, so a process on a wrong working folder would lead incorrect build result.

**Comment by thegrahamking** [comment]
@lifengl I suspect you should have been tagged by github actions above.  Obviously this issue isn't stale.  Could you please do the necessary to prevent inadvertant closure?

**Comment by thegrahamking** [comment]
This is partially resolved v1.5.20.

Build now uses the correct SDK
``` 
 *  Executing task: dotnet: build 

dotnet build C:\src\temp\vscode-dotnet-sdk-test\vscode-dotnet-sdk-test.sln /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary 
Microsoft (R) Build Engine version 17.0.1+b177f8fa7 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  classlib -> C:\src\temp\vscode-dotnet-sdk-test\src\classlib\bin\Debug\net6.0\classlib.dll
```
C# Dev Kit - Test Explorer still uses latest SDK
```
reated Test Controller
Using vstest from dotnet sdk in [C:\Program Files\dotnet\sdk\8.0.204].
Initialized Test Explorer Server [17888]
Test Store Folder: c:\Users\graking\AppData\Roaming\Code\User\workspaceStorage\91b8208d80f28ce75bc451c8ae0ca4e9\ms-dotnettools.csdevkit
Test data store opened in 0.024 sec.
Initialized project system provider.
```

**Comment by adrianvmsft** [comment]
Thank you for confirming that the fix to donet build task works.
@peterwald It looks like the Test Explorer issue may be a different issue, could you please take a look?

**Comment by ocallesp** [comment]
@webreidi @AbhitejJohn 
Test Explorer in C# DevKit is not taking into consideration global.json. The source code is pretty much is looking for the list of available SDKs and take the latest.

I am working on a fix....

**Comment by lifengl** [comment]
The global.json is based on the working folder, so any logic starts a command must set working folder correctly.

**Comment by ocallesp** [comment]
Fixed. It will available in the next release.

**Comment by thegrahamking** [comment]
@ocallesp which release is next?  

Tried in v1.9.55 and test explorer is still using .NET 8
```
Created Test Controller
Using vstest from dotnet sdk in [C:\Program Files\dotnet\sdk\8.0.303].
Initialized Test Explorer Server [62644]
Test Store Folder: c:\Users\GrahamKing\AppData\Roaming\Code\User\workspaceStorage\ffddd23836b3753782968b095efd69de\ms-dotnettools.csdevkit
Test data store opened in 0.022 sec.
Initialized project system provider.
```

**Comment by peterwald** [comment]
@thegrahamking The fix should be in the next pre-release version (after 1.10.4).

**Comment by thegrahamking** [comment]
@peterwald @ocallesp 
I've tested with pre-release `1.10.6` and found that if the _exact_ SDK version is available then everything works as expected:

```
> dotnet --list-sdks
6.0.425 [C:\Program Files\dotnet\sdk]
8.0.304 [C:\Program Files\dotnet\sdk]
```
`global.json`
``` json
{
    "sdk": {
      "version": "6.0.425",
      "rollForward": "latestFeature"
    }
  }
```
C# Dev Kit - Test Explorer
```
Created Test Controller
platform: win32 arch: x64
Using vstest from dotnet sdk in [C:\Program Files\dotnet\sdk\6.0.425].
Initialized Test Explorer Server [29908]
Test Store Folder: c:\Users\GrahamKing\AppData\Roaming\Code\User\workspaceStorage\ffddd23836b3753782968b095efd69de\ms-dotnettools.csdevkit
Test data store opened in 0.023 sec.
Initialized project system provider.
```

However, the `rollForward` element is being ignored, i.e. if the _exact_ SDK version is not available we get an error (note the change in version in `global.json`:
```
> dotnet --list-sdks
6.0.425 [C:\Program Files\dotnet\sdk]
8.0.304 [C:\Program Files\dotnet\sdk]
```
`global.json`
``` json
{
    "sdk": {
      "version": "6.0.100",
      "rollForward": "latestFeature"
    }
  }
```
C# Dev Kit - Test Explorer
```
Created Test Controller
platform: win32 arch: x64
unable to create test controller for c# extension: Error: SDK version 6.0.100 not found.
```
This is the same with `rollForward` set to `latestMajor`, `latestMinor` and `latestPatch` as well.

Build works as expected (i.e. issue resolved for build)

**Comment by thegrahamking** [comment]
I've tested with release `1.10.18` and confirmed this is now all working as expected (build and test explorer).  Thanks for your efforts.
